#!/bin/bash
apt install -y curl

# curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
# curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
apt install -y nodejs

npm install -g @angular/cli@7.2.2 --save-dev
npm install -g --save-dev @angular-devkit/build-angular
